---
certbot_script: "{{ (ansible_os_family == 'Debian') | ternary('/usr/bin/certbot', '/bin/certbot') }}"
# Certbot auto-renew cron job configuration (for certificate renewals).
certbot_auto_renew: true
certbot_auto_renew_user: "{{ ansible_user }}"
certbot_auto_renew_hour: 3
certbot_auto_renew_minute: 30
certbot_auto_renew_options: "--quiet --no-self-upgrade"

# Parameters used when creating new Certbot certs.
certbot_create_if_missing: no
certbot_create_method: standalone
certbot_admin_email: ben.ebsworth@gmail.com
certbot_certs: []
  # - email: janedoe@example.com
  #   domains:
  #     - example1.com
  #     - example2.com
  # - domains:
  #     - example3.com
certbot_create_command: "{{ certbot_script }} certonly --standalone --agree-tos --email {{ cert_item.email | default(certbot_admin_email) }} -d {{ cert_item.domains | join(',') }}"