---
- name: deploy spot instances
  hosts: localhost
  gather_facts: false
  vars_files:
    - config/config.yml
  roles:
    - ec2
    - dns

- name: baseline instances
  hosts: backend:frontend
  become: yes
  vars:
    docker_install_compose: false
    pip_install_packages:
      - name: docker
      - name: docker-compose
  tags:
    - configure
    - common
  roles:
    - common
    - geerlingguy.docker

- name: deploy containers
  hosts: backend
  become: yes
  vars:
    compose_project: elasticsearch-compose.yml
  tags:
    - elasticsearch
  roles:
    - elasticsearch-docker


- name: initialise certs for frontend
  hosts: frontend
  become: yes
  vars:
    cert_item:
      email: ben.ebsworth@gmail.com
      domains:
        - www.nutry.net
        - nutry.net
  tags:
    - certs
    - letsencrypt
  roles:
    - letsencrypt

- name: deploy frontend containers
  hosts: frontend
  become: yes
  vars:
    compose_project: webapp-compose.yml
  tags:
    - webapp
  roles:
    - webapp-docker

