export const AGES = [
  { value: 'I1', label: 'Infant (0m-6m)', className: 'infant1' },
  { value: 'I2', label: 'Infant (7m-12m)', className: 'infant2' },
  { value: 'C1', label: 'Children (1-3)', className: 'children1' },
  { value: 'C2', label: 'Children (4-8)', className: 'children1' },
  { value: 'B1', label: 'Boys (9-13)', className: 'boys1' },
  { value: 'B2', label: 'Boys (14-16)', className: 'boys2' },
  { value: 'G1', label: 'Girls (9-13)', className: 'girls1' },
  { value: 'G2', label: 'Girls (14-16)', className: 'girls2' },
  { value: 'AM19', label: 'Adult Male (19-30)', className: 'am-19' },
  { value: 'AM31', label: 'Adult Male (31-50)', className: 'am-31' },
  { value: 'AM51', label: 'Adult Male (51-70)', className: 'am-51' },
  { value: 'AM71', label: 'Adult Male (71-)', className: 'am-71' },
  { value: 'AF19', label: 'Adult Female (19-30)', className: 'af-19' },
  { value: 'AF31', label: 'Adult Female (31-50)', className: 'af-31' },
  { value: 'AF51', label: 'Adult Female (51-70)', className: 'af-51' },
  { value: 'AF71', label: 'Adult Female (71-)', className: 'af-71' },
  { value: 'P1', label: 'Pregnant (14-18)', className: 'preg-14' },
  { value: 'P2', label: 'Pregnant (19-31)', className: 'preg-19' },
  { value: 'P3', label: 'Pregnant (31-50)', className: 'preg-31' },
  { value: 'L1', label: 'Lactation (14-18)', className: 'lac-14' },
  { value: 'L2', label: 'Lactation (19-30)', className: 'lac-19' },
  { value: 'L3', label: 'Lactation (31-50)', className: 'lac-31' },
];
