- name: stop nginx
  service:
    name: nginx
    state: stopped
- stat: path=/etc/letsencrypt/live/{{ cert_item.domains[0] }}
  register: certs_stats

- debug: var=certs_stats

- name: deliver nginx configuration to server
  template: src=nginx.conf.j2 dest=/etc/nginx/nginx.conf

- name: Generate new certificate if one doesn't exist
  command: "{{ certbot_create_command }}"
  args:
    creates: /etc/letsencrypt/live/{{ cert_item.domains[0] }}
  when: not certs_stats.stat.isdir

- name: stop nginx
  service:
    name: nginx
    state: started
