
- name: os family
  debug: var=ansible_os_family
- block:
  - name: Install EPEL repo.
    yum:
      name: https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
      state: present
  - name: Import EPEL GPG key.
    rpm_key:
      key: /etc/pki/rpm-gpg/RPM-GPG-KEY-EPEL-7
      state: present
  - name: update packages
    yum:
      name: "*"
      state: latest
  - name: install certbot
    yum:
      name: "{{ item }}"
    with_items:
      - nginx
      - certbot-nginx
  when: ansible_os_family == "RedHat"
  tags:
    - letsencrypt
    - certs

- block:
  - name: add repositorties
    apt_repository:
      repo: "{{ item }}"
      update_cache: yes
      validate_certs: yes
      state: present
    with_items:
      - ppa:nginx/stable
      - ppa:certbot/certbot
  - name: install certbox packages and nginx
    apt:
      name: "{{ item }}"
      state: present
    with_items:
      - nginx
      - python-certbot-nginx
  when: ansible_os_family == "Debian"

- block:
  - import_tasks: create_certs.yml
  tags:
    - letsencrypt
    - certs