names = {
    'ENERC': 'Energy',
    'ENERC_KCAL': 'Energy',
    'ASH': 'Ash',
    'NT': 'Nitrogen, Total',
    'RIBF': 'Riboflavin',
    'WATER': 'Water',
    'FATRN': 'Total trans fatty acids',
    'FATRNF': 'Total trans fatty acids (%)',
    'FATRNM': 'Total monounsaturated trans fatty acids',
    'FATRNMF': 'Total monounsaturated trans fatty acids (%)',
    'FATRNP': 'Total polyunsaturated trans fatty acids',
    'FATRNPF': 'Total polyunsaturated trans fatty acids (%)',
    'F18D2T9T12': 'C18:2T9T12',
    'F18D2T9T12F': 'C18:2T9T12FD',
    'F18D3T9T12T15F': 'C18:3T9T12T15',
    'F18D3T9T12T15FD': 'C18:3T9T12T15FD',
    'F18D2TF': 'C18:3TFD',
    'F18D2TN6': 'C18:2Tw6FD',
    'F18D2TN6F': 'C18:2Tw6',
    'F18D2CLAFD': 'C18:2CLA',
    'F18D2CLAF': 'C18:2CLA',
    'F18D1TN9F': 'C18:1T9',
    'F18D1TN9': 'C18:1T9FD',
    'F18D1TN7F': 'C18:1w7',
    'F18D1TF': 'C18:1T',
    'F18D1T': 'C18:1T',
    'F18D1N7': 'C18:1T7FD',
    'F16D1TF': 'C16:1',
    # Carbohydrates
    'CHOCDF': 'Carbohydrate, by difference',
    'CHOAVL': 'Available carbohydrate',
    'SUGAR': 'Sugar Total',
    'FIBTG': 'Dietary Fibre',
    'SUCS': 'Sucrose',
    'MALS': 'Maltose',
    'GALS': 'Galactose',
    'FRUS': 'Fructose',
    'GLUS': 'Glucose',
    'LACS': 'Lactose',
    'STARCH': 'Starch',
    # common
    'DEXTN': 'Dextrin',
    'GYRL': 'Glycerol',
    'GLYC': 'Glycogen',
    'INULN': 'Inulin',
    'MANTL': 'Mannitol',
    'MALTDEX': 'Maltodextrin',
    'OLSAC': 'Oligosaccharides',
    'RAFS': 'Raffinose',
    'STAS': 'Stachyose',
    'SORTL': 'Sorbitol',

    # Protiens & amino acids
    'PROCNT': 'Protein',
    'TRP': 'Tryptophan',
    'TYR': 'Tyrosine',
    'THR': 'Threonine',
    'SER': 'Serine',
    'ALA': 'Alanine',
    'ARG': 'Arginine',
    'ASP': 'Aspartic acid',
    'CYS': 'Cystine',
    'HIS': 'Histidine',
    'HISTN': 'Histidine',
    'ILE': 'Isoleucine',
    'HYP': 'Hyroxyprofile',
    'PRO': 'Proline',
    'GLU': 'Glutamic acid',
    'GLY': 'Glycine',
    'PHE': 'Phenylalanine',
    'MET': 'Methionine',
    'LYS': 'Lysine',
    'LEU': 'Leucine',
    'VAL': 'Valine',
    'TRP_G': 'Tryptophan',
    'TYR_G': 'Tyrosine',
    'THR_G': 'Threonine',
    'SER_G': 'Serine',
    'ALA_G': 'Alanine',
    'ARG_G': 'Arginine',
    'ASP_G': 'Aspartic acid',
    'CYS_G': 'Cystine',
    'HIS_G': 'Histidine',
    'HISTN_G': 'Histidine',
    'ILE_G': 'Isoleucine',
    'HYP_G': 'Hyroxyprofile',
    'PRO_G': 'Proline',
    'GLU_G': 'Glutamic acid',
    'GLY_G': 'Glycine',
    'PHE_G': 'Phenylalanine',
    'MET_G': 'Methionine',
    'LYS_G': 'Lysine',
    'LEU_G': 'Leucine',
    'VAL_G': 'Valine',
    # Fats & fatty acids
    'FAT': 'Total lipid (fat)',
    'FAMS': 'Fatty acids, total monounsaturated',
    'FAPU': 'Fatty acids, total polyunsaturated',
    'FASAT': 'Fatty acids, total saturated',
    'FATSAT': 'Fatty acids, total saturated',
    'F4D0': '4:0',
    'F4D0F': '4:0',
    'F6D0': '6:0',
    'F6D0F': '6:0',
    'F8D0': '8:0',
    'F8D0F': '8:0',
    'F10D0': '10:0',
    'F10D0F': '10:0',
    'F10D1': '10:1',
    'F10D1F': '10:1',
    'F12D0': '12:0',
    'F12D0F': '12:0',
    'F13D0': '13:0',
    'F14D0': '14:0',
    'F14D1': '14:1',
    'F15D0': '15:0',
    'F15D1': '15:1',
    'F16D0': '16:0',
    'F16D1': '16:1 undifferentiated',
    'F16D1T': '16:0T',  # trans
    'F16D1C': '16:0C',  # cis
    'F17D0': '17:0',
    'F17D1': '17:1',
    'F18D0': '18:0',
    'F18D1C': '18:1 C',
    'F18D1TN7': '18:1 T7',
    'F18D1': '18:1 undifferentiated',
    'F18D2': '18:2 undifferentiated',
    'F18D2CN6': '18:2 c n-6',
    'F18D2TT': '18:2 TT',
    'F18D2I': '18:2 I',
    'F18D2N6': '18:2 n-6',
    'F18D3': '18:3 undifferentiated',
    'F18D3T': '18:3 T',
    'F18D3I': '18:3 I',
    'F18D3N6': '18:3 n-6',
    'F18D3N3F': '18:3 n-3',  # per unit
    'F18D3N3': '18:3 n-3',  # per %
    'F18D4': '18:4',
    'F18D4N3': '18:4 n-3',
    'F19D0': '19:0',
    'F19D0F': '19:0',
    'F20D0': 'Fatty Acid 20:0',
    'F20D1': 'Fatty Acid 20:1',
    'F20D1F': 'Fatty Acid 20:1',
    'F20D1N11F': '20:1 n-11',
    'F20D2N6': '20:2 n-6 c,c',
    'F20D3N3': '20:2 n-3',
    'F20D0F': '20:0',
    'F20D3': '20:3 undifferentiated',
    'F20D4': '20:4 undifferentiated',
    'F20D4N6': '20:4 n-6',
    'F20D5': '20:5 n-3 (EPA)',
    'F21D0': '21:0',
    'F22D0': '22:0',
    'F22D1': '22:1 undifferentiated',
    'F22D1C': '22:1 c',
    'F22D1T': '22:1 t',
    'F22D3': '20:2 n-3',
    'F22D5N3': '22:5 n-3 (DPA)',
    'F22D6': '22:6',
    'F22D6N3': '22:6 n-3 (DHA)',
    'F23D0': '23:0',
    'F24D0': '24:0',
    'F24D1': '24:1',
    'F24D1C': '24:1 c',
    'LCW3TOTAL': 'Total Omega 3 Fatty Acid',
    'FAUNDIFF': 'Undifferentiated fatty acids',

    # acids
    'ACEAC': 'Acetic acid',
    'CITAC': 'Citric acid',
    'FUMAC': 'Fumaric acid',
    'LACAC': 'Lactic acid',
    'MALAC': 'Malic acid',
    'OXALAC': 'Oxalic acid',
    'PROPAC': 'Propionic acid',
    'QUINAC': 'Quinic acid',
    'SHIKAC': 'Shikimic acid',
    'SUCAC': 'Succinic acid',
    'TARAC': 'Tartaric acid',

    #        prefixToName[""]': ",
    # Minerals & metals
    'AL': 'Aluminium',
    'AS': 'Arsenic',
    'CA': 'Calcium (Ca)',
    'CD': 'Cadmium (Cd)',
    'CU': 'Copper (Cu)',
    'CO': 'Cobalt (Co)',
    'CR': 'Chromium (Cr)',
    'FD': 'Fluoride (F)',
    'FE': 'Iron (Fe)',
    'HG': 'Mercury (Hg)',
    'ID': 'Iodine (I)',
    'K': 'Potassium (K)',
    'MG': 'Magnesium (Mg)',
    'MN': 'Manganese (Mn)',
    'M0': 'Molybdenum (Mo)',
    'NA': 'Sodium (Na)',
    'NI': 'Nickel (Ni)',
    'P': 'Phosphorus (P)',
    'PB': 'Lead (Pb)',
    'S': 'Sulphur (S)',
    'SE': 'Selenium (Se)',
    'SN': 'Tin (Sn)',
    'ZN': 'Zinc (Zn)',
    'FLD': 'Flouride (F)',
    # Vitamins
    'BIOT': 'Biotin (B7)',
    'B1': 'Thiamin (B1)',
    'THIA': 'Thiamin (B1)',
    'B2': 'Riboflavin (B2)',
    'B3': 'Niacin (B3)',
    'VITB6': 'Pyridoxine (B6)',
    'VITB12': 'Cobalamin (B12)',
    'CARTA': 'Alpha carotene',
    'CARTB': 'Beta carotene',
    'CARTBEQ': 'Beta carotene equivalents',
    'CHOLN': 'Choline',
    'BETN': 'Betaine',
    'CRYPX': 'Cryptoxanthin',
    'NIA': 'Niacin (B3)',
    'NIAEQ': 'Niacin Equivalents',

    'FOL': 'Total folates',
    'FOLAC': 'Folic acid',
    'FOLFD': 'Folate, natural',
    'FOLDFE': 'Dietary folate equivalents',
    'LUT+ZEA': 'Lutein + Zeaxanthin',
    'LUTN': 'Lutein',
    'LYCPN': 'Lycopene',

    'MK4': 'Menaquinone-4',
    'PANTAC': 'Pantothenic acid (B5)',
    'VITB6A': 'Pyridoxine (B6)',
    'VITE': 'Vitamin E',
    'VITK': 'Vitamin K (phylloquinone)',
    'VITK1D': '',
    'RETOL': 'Retinol',
    'VITA_IU': 'Retinol Equivalents (VIT A)',
    'VITA_RAE': 'Retinol Activity Equivalent (RAE)',
    'VITA': 'Retinol Equivalents (VIT A)',
    'VITC': 'Vitamin C',
    # vit d
    'CHOCAL': 'Cholecalciferol (D3)',
    'ERGCAL': 'Ergocalciferol (D2)',
    'CHOCALOH': '25-OH Cholecalciferol (25-OH D3)',
    'ERGCALOH': '25-OH Ergocalciferol (25-OH D2)',
    'VITDEQ': 'Vitamin D3 equivalents, with factors',
    'VITD': 'Vitamin D',
    # sterols
    'PHYSTR': 'Phytosterols',
    'STID7': 'Stigmasterol',  # usually delta 7-stigmasterol
    'CAMD5': 'Campesterol',
    'SITSTR': 'Sitosterol',
    'TOCPHA': 'Alpha-tocopherol',
    'TOCTRA': 'Alpha-tocotrienol',
    'TOCPHB': 'Beta-tocopherol',
    'TOCTRB': 'Beta-tocotrienol',
    'TOCPHD': 'Delta-tocopherol',
    'TOCTRD': 'Delta-tocotrienol',
    'TOCPHG': 'Gamma-tocopherol',
    'TOCTRG': 'Gamma-tocotrienol',
    # Other
    'CAFFN': 'Caffeine',
    'CHOLE': 'Cholesterol',
}
