version: '2'
services:
  webapp:
    build:
      context: .
      dockerfile: ./internals/docker/Dockerfile
      args:
        ELASTICSEARCH_PROXY_HOST: localhost
        ELASTICSEARCH_PROXY_PORT: 8443
        ELASTICSEARCH_PROXY_MODE: https
        ELASTICSEARCH_PROXY_PREFIX: /v1/search
        FIREBASE_ENDPOINT: https://nutry-v1.firebaseio.com
        FIREBASE_DB_VERSION: v1
    environment:
      ELASTICSEARCH_PROXY_HOST: localhost
      ELASTICSEARCH_PROXY_PORT: 8443
      ELASTICSEARCH_PROXY_MODE: https
      ELASTICSEARCH_PROXY_PREFIX: /v1/search
      FIREBASE_ENDPOINT: https://nutry-v1.firebaseio.com
      FIREBASE_DB_VERSION: v1
    ports:
      - "3000:3000"
  proxy:
    build:
      context: ./internals/proxy/
      args:
        SERVER_NAME: localhost
        WEBAPP_PORT: 3000
        ELASTICSEARCH_PROXY_PREFIX: /v1/search/
        ELASTICSEARCH_PROXY_HOST: elasticsearch1
        ELASTICSEARCH_PROXY_PORT: 9200
    env_file:
      - .env
    depends_on:
      - webapp
    ports:
      - "8080:80"
      - "8443:443"

networks:
  default:
    external:
      name: docker_esnet